[package]
name = "presuborg"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "0.2.11"
serde = { version = "1.0.193", features = ["derive"] }
serde_json = "1.0.108"
sevenz-rust = "0.5.3"
